"""
Integrated Multi-Agent Workflow:
- Backend Synthesis Architect (Gemini) monitors Knowledge Graph
- LangGraph Manager (DeepSeek via Fireworks) coordinates project ranking
- MongoDB Atlas for shared memory
"""
import os
import sys
import json
from datetime import datetime
from dotenv import load_dotenv
from pymongo import MongoClient
from typing import List, Dict, Any

# Load environment variables
load_dotenv('.env.local')

# Add src to path for LangGraph workflow
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'backend'))

from agents.langgraph_workflow import create_ranking_workflow, logger

def get_mongodb_connection():
    """Get MongoDB client with proper URI"""
    mongodb_uri = os.getenv("MONGODB_URI")
    if not mongodb_uri:
        raise ValueError("MONGODB_URI not set in .env.local")
    
    logger.log(f"Connecting to MongoDB Atlas...", "INFO")
    try:
        client = MongoClient(mongodb_uri)
        # Test connection
        client.admin.command('ping')
        logger.log("✓ Connected to MongoDB Atlas", "SUCCESS")
        return client
    except Exception as e:
        logger.log(f"✗ MongoDB connection failed: {e}", "ERROR")
        raise

def fetch_proposals_from_synthesis_architect(db_client) -> List[Dict[str, Any]]:
    """
    Fetch project proposals generated by the Synthesis Architect
    from the Project_Proposals collection
    """
    try:
        db = db_client["AcademicPlanner"]
        proposals = list(db["Project_Proposals"].find().sort("timestamp", -1).limit(5))
        
        logger.log(f"✓ Retrieved {len(proposals)} proposals from Synthesis Architect", "SUCCESS")
        
        # Convert to format expected by LangGraph workflow
        projects = []
        for proposal in proposals:
            projects.append({
                "name": proposal.get("title", "Untitled Project"),
                "complexity": proposal.get("difficulty", "medium").lower(),
                "due_date": "2026-01-24",  # Default, could be enhanced
                "estimated_hours": 8,
                "rationale": proposal.get("rationale", ""),
                "first_step": proposal.get("first_step", "")
            })
        
        return projects
    
    except Exception as e:
        logger.log(f"Error fetching proposals: {e}", "ERROR")
        return []

def export_results_to_json(final_state: Dict[str, Any]):
    """Export top 3 ranked projects to JSON file"""
    try:
        output_file = "top_3_projects.json"
        
        # Prepare data for export
        export_data = {
            "timestamp": datetime.now().isoformat(),
            "model": final_state.get('metadata', {}).get('deepseek_model', 'N/A'),
            "total_projects_analyzed": len(final_state.get('projects', [])),
            "top_3_projects": []
        }
        
        # Add top 3 ranked projects
        for result in final_state.get('ranked_results', [])[:3]:
            project_data = {
                "rank": result.get('rank'),
                "name": result.get('project', {}).get('name'),
                "priority_score": result.get('priority_score'),
                "complexity": result.get('project', {}).get('complexity'),
                "due_date": result.get('project', {}).get('due_date'),
                "estimated_hours": result.get('project', {}).get('estimated_hours'),
                "decision": result.get('decision'),
                "rationale": result.get('project', {}).get('rationale', ''),
                "first_step": result.get('project', {}).get('first_step', '')
            }
            export_data['top_3_projects'].append(project_data)
        
        # Write to JSON file
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(export_data, f, indent=2, ensure_ascii=False)
        
        logger.log(f"\n✓ Exported top 3 projects to {output_file}", "SUCCESS")
        
    except Exception as e:
        logger.log(f"Error exporting to JSON: {e}", "ERROR")

def check_environment():
    """Check if environment is properly configured"""
    logger.log_separator("ENVIRONMENT CHECK")
    
    # Check MongoDB URI
    mongodb_uri = os.getenv("MONGODB_URI")
    if mongodb_uri:
        logger.log(f"✓ MONGODB_URI set", "SUCCESS")
    else:
        logger.log("✗ MONGODB_URI not set", "ERROR")
        return False
    
    # Check Fireworks API Key
    fireworks_key = os.getenv("FIREWORKS_API_KEY")
    if fireworks_key:
        logger.log(f"✓ FIREWORKS_API_KEY set ({fireworks_key[:10]}...)", "SUCCESS")
    else:
        logger.log("✗ FIREWORKS_API_KEY not set", "ERROR")
        return False
    
    # Check Gemini API Key (optional for synthesis architect)
    gemini_key = os.getenv("GEMINI_API_KEY")
    if gemini_key and gemini_key != "your_gemini_api_key_here":
        logger.log(f"✓ GEMINI_API_KEY set (Synthesis Architect enabled)", "SUCCESS")
    else:
        logger.log("⚠ GEMINI_API_KEY not set (Synthesis Architect disabled)", "WARNING")
    
    return True

def main():
    """Run the integrated workflow"""
    
    # Check environment first
    if not check_environment():
        logger.log("\n❌ Environment check failed. Please fix issues above.", "ERROR")
        logger.log("\nUpdate your .env.local file with:", "INFO")
        logger.log("  MONGODB_URI=mongodb+srv://<db_username>:<db_password>@cluster0.fim9iq.mongodb.net/?appName=Cluster0", "INFO")
        logger.log("  FIREWORKS_API_KEY=your_fireworks_key_here", "INFO")
        logger.log("  GEMINI_API_KEY=your_gemini_key_here (optional)", "INFO")
        return None
    
    logger.log_separator("INTEGRATED MULTI-AGENT WORKFLOW")
    logger.log("Architecture:", "INFO")
    logger.log("  1. Synthesis Architect (Gemini) → generates project proposals", "INFO")
    logger.log("  2. LangGraph Manager (DeepSeek) → coordinates ranking workflow", "INFO")
    logger.log("  3. MongoDB Atlas → shared memory across agents", "INFO")
    logger.log(f"Timestamp: {datetime.now().isoformat()}", "INFO")
    
    # Connect to MongoDB
    try:
        db_client = get_mongodb_connection()
    except Exception as e:
        logger.log(f"Cannot proceed without MongoDB connection", "ERROR")
        return None
    
    # Fetch proposals from Synthesis Architect
    logger.log_separator("FETCHING PROPOSALS FROM SYNTHESIS ARCHITECT")
    projects = fetch_proposals_from_synthesis_architect(db_client)
    
    if not projects:
        logger.log("⚠ No proposals found. Using sample projects...", "WARNING")
        # Fallback to sample projects
        projects = [
            {
                "name": "Learn Data Visualization with Python",
                "complexity": "medium",
                "due_date": "2026-01-24",
                "estimated_hours": 8
            },
            {
                "name": "Write Essay on AI & Education",
                "complexity": "medium",
                "due_date": "2026-01-18",
                "estimated_hours": 8
            },
            {
                "name": "Build Traffic Flow Simulator",
                "complexity": "medium",
                "due_date": "2026-01-14",
                "estimated_hours": 8
            }
        ]
    
    logger.log(f"Projects to analyze: {len(projects)}", "INFO")
    for i, proj in enumerate(projects, 1):
        logger.log(f"  {i}. {proj['name']}", "INFO")
    
    # Create LangGraph workflow
    logger.log("\nBuilding LangGraph workflow...", "INFO")
    app = create_ranking_workflow()
    
    # Initial state
    initial_state = {
        "projects": projects,
        "sprint_context": {},
        "analyzed_projects": [],
        "ranked_results": [],
        "metadata": {}
    }
    
    # Execute workflow
    logger.log_separator("EXECUTING LANGGRAPH WORKFLOW")
    
    try:
        final_state = app.invoke(initial_state)
        
        logger.log_separator("FINAL RESULTS")
        logger.log("Top Projects:", "SUCCESS")
        for result in final_state['ranked_results']:
            logger.log(
                f"Rank {result['rank']}: {result['project']['name']} "
                f"(Score: {result['priority_score']:.1f})", 
                "SUCCESS"
            )
            if 'rationale' in result['project']:
                logger.log(f"  Rationale: {result['project']['rationale'][:100]}...", "INFO")
        
        # Show metadata
        if 'metadata' in final_state and 'deepseek_invoked_at' in final_state['metadata']:
            logger.log(f"\n📊 Metadata:", "INFO")
            logger.log(f"  Model: {final_state['metadata'].get('deepseek_model', 'N/A')}", "INFO")
            logger.log(f"  Invoked at: {final_state['metadata'].get('deepseek_invoked_at', 'N/A')}", "INFO")
        
        # Export top 3 projects to JSON
        export_results_to_json(final_state)
        
        db_client.close()
        return final_state
        
    except Exception as e:
        logger.log(f"Workflow failed: {e}", "ERROR")
        import traceback
        traceback.print_exc()
        db_client.close()
        return None

if __name__ == "__main__":
    main()
