import { NextResponse } from 'next/server';
import { readFileSync } from 'fs';
import { join } from 'path';

/**
 * GET /api/top-projects
 * Returns the top 3 ranked projects from the Python multi-agent workflow
 * Data is read from top_3_projects.json generated by run_integrated_workflow.py
 */
export async function GET() {
  try {
    // Read the JSON file generated by the Python backend
    const filePath = join(process.cwd(), 'top_3_projects.json');
    const fileContents = readFileSync(filePath, 'utf8');
    const data = JSON.parse(fileContents);

    return NextResponse.json({
      success: true,
      data: data,
      source: 'Python Multi-Agent Workflow (DeepSeek + MongoDB)',
    });
  } catch (error: any) {
    // If file doesn't exist or can't be read, return error
    if (error.code === 'ENOENT') {
      return NextResponse.json(
        {
          success: false,
          error: 'Top projects file not found. Run: python run_integrated_workflow.py',
          message: 'The Python backend workflow needs to be executed first.',
        },
        { status: 404 }
      );
    }

    return NextResponse.json(
      {
        success: false,
        error: 'Failed to read top projects',
        details: error.message,
      },
      { status: 500 }
    );
  }
}

/**
 * POST /api/top-projects/refresh
 * Triggers the Python workflow to regenerate the rankings
 */
export async function POST() {
  try {
    const { spawn } = require('child_process');
    const process = spawn('python', ['run_integrated_workflow.py'], {
      cwd: process.cwd(),
    });

    // Return immediately - workflow runs in background
    return NextResponse.json({
      success: true,
      message: 'Workflow triggered. Rankings will be updated shortly.',
      status: 'running',
    });
  } catch (error: any) {
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to trigger workflow',
        details: error.message,
      },
      { status: 500 }
    );
  }
}
